version: "3.3"

networks:
    overnet:
      external:
          name: overnet

services:
    filler:
        image: "jcrecio/flipi-filler:latest"
        command: python main.py
        networks:
            - overnet
        volumes:
            - .:/flights
        # links:
        #     - flightsdatabase
    # flightsapi:
    #     # image: ${DOCKER_REGISTRY-}flightsapi
    #     build:
    #         context: .
    #         dockerfile: Flipi.FlightsManager/Dockerfile
    #     volumes:
    #         - .:/flights
    #     links:
    #         - flightsdatabase
    # flightsdatabase:
    #     image: mongo:latest
    #     deploy:
    #         restart_policy:
    #             condition: always
    #     ports:
    #         - "37017:27017"