version: "3.3"
services:
    flightsapi:
        image: ${DOCKER_REGISTRY-}flightsapi
        build:
            context: .
            dockerfile: Flipi.FlightsManager/Dockerfile
        volumes:
            - .:/flights
        links:
            - flightsdatabase
    filler:
        image: ${DOCKER_REGISTRY-}filler
        build:
            context: .
            dockerfile: Flipi.Filler/Dockerfile
        volumes:
            - .:/flights
        links:
            - flightsdatabase
    flightsdatabase:
        image: mongo:latest
        deploy:
            restart_policy:
                condition: always
        ports:
            - "37017:27017"