version: "3.3"

networks:
    overnet:
      external:
          name: overnet

services:
    filler:
        image: "jcrecio/flipi-filler:latest"
        command: node index.js
        networks:
            - overnet
        ports:
            - "8191:8191"
        volumes:
            - .:/flights
    flightsdatabase:
        image: mongo:latest
        networks:
            - overnet
        ports:
            - "17017:17017"
    # flightsapi:
    #     # image: ${DOCKER_REGISTRY-}flightsapi
    #     build:
    #         context: .
    #         dockerfile: Flipi.FlightsManager/Dockerfile
    #     volumes:
    #         - .:/flights
    #     links:
    #         - flightsdatabase